### ISSUE TITLE
Environment tikzpicture undefined. \begin{ tikzpicture }

### ISSUE THREAD

**Issue by AbdelhamidAITMHID** [kellertuer/TUKL-Design#3]
I'm new to LaTeX, I want to draw some shapes with Tikz. It gives me this error: Environment tikzpicture undefined. \begin{ tikzpicture }.
my code is as follows:

\documentclass[a4paper, 12pt]{report}
\usepackage{lmodern}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{pgfplots}
\usepackage{tikz}
\usepackage{ amsmath, amssymb, amsfonts}
\begin{document}
\begin{ tikzpicture } 
\draw (-2,0) - (2,0); 
\filldraw [ gris ] (0,0) cercle (2pt); 
\draw (-2, -2) .. contrôles (0,0) .. (2, -2); 
\draw (-2,2) .. contrôles (-1,0) et (1,0) .. (2,2); 
\end{ tikzpicture } 
\end{document}

please help

**Comment by kellertuer** [comment]
I am sorry, this seems to be unrelated to this beamer style, can you use a forum like https://tex.stackexchange.com for such questions?

The main problem with that code is, you have to many spaces the correct line (also for the `\end` is not
````
\begin{ tikzpicture }
````
but
````
\begin{tikzpicture}
````
and the same for the space in front of `amsmath` i think.

**Comment by AbdelhamidAITMHID** [comment]
> I am sorry, this seems to be unrelated to this beamer style, can you use a forum like https://tex.stackexchange.com for such questions?
> 
> The main problem with that code is, you have to many spaces the correct line (also for the `\end` is not
> 
> ```
> \begin{ tikzpicture }
> ```
> 
> but
> 
> ```
> \begin{tikzpicture}
> ```
> 
> and the same for the space in front of `amsmath` i think.

thanks #kellertuer  for your suggestion i will fix that & try again
